### ISSUE TITLE
Connection type is not set.

### ISSUE THREAD

**Issue by neetu-goyal** [eWAYPayment/eway-rapid-php#16]
http://petceutics2.testpad.com.au/checkout/

error on checkout page 

1 exception(s):
Exception #0 (Magento\Framework\Exception\PaymentException): Connection type is not set.

Exception #0 (Magento\Framework\Exception\PaymentException): Connection type is not set.
#0 /var/www/html/dev.petceutics.com.au/app/code/Eway/EwayRapid/Model/Method/Adapter.php(480): Eway\EwayRapid\Model\Method\Adapter->getMethodInstance()
#1 /var/www/html/dev.petceutics.com.au/generated/code/Eway/EwayRapid/Model/Method/Adapter/Interceptor.php(492): Eway\EwayRapid\Model\Method\Adapter->getConfigData('sort_order', '1')
#2 /var/www/html/dev.petceutics.com.au/vendor/magento/module-payment/Model/PaymentMethodList.php(58): Eway\EwayRapid\Model\Method\Adapter\Interceptor->getConfigData('sort_order', '1')
#3 [internal function]: Magento\Payment\Model\PaymentMethodList->Magento\Payment\Model\{closure}(Object(Eway\EwayRapid\Model\Method\Adapter\Interceptor), Object(Magento\Authorizenet\Model\Directpost\Interceptor))
#4 /var/www/html/dev.petceutics.com.au/vendor/magento/module-payment/Model/PaymentMethodList.php(59): uasort(Array, Object(Closure))
#5 /var/www/html/dev.petceutics.com.au/vendor/magento/module-payment/Model/PaymentMethodList.php(84): Magento\Payment\Model\PaymentMethodList->getList('1')
#6 /var/www/html/dev.petceutics.com.au/vendor/magento/module-vault/Plugin/PaymentVaultConfigurationProcess.php(63): Magento\Payment\Model\PaymentMethodList->getActiveList('1')
#7 /var/www/html/dev.petceutics.com.au/vendor/magento/framework/Interception/Interceptor.php(121): Magento\Vault\Plugin\PaymentVaultConfigurationProcess->beforeProcess(Object(Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor), Array)
#8 /var/www/html/dev.petceutics.com.au/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->Magento\Framework\Interception\{closure}(Array)
#9 /var/www/html/dev.petceutics.com.au/generated/code/Magento/Checkout/Block/Checkout/LayoutProcessor/Interceptor.php(26): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->___callPlugins('process', Array, Array)
#10 /var/www/html/dev.petceutics.com.au/vendor/magento/module-checkout/Block/Onepage.php(78): Magento\Checkout\Block\Checkout\LayoutProcessor\Interceptor->process(Array)
#11 /var/www/html/dev.petceutics.com.au/vendor/magento/module-checkout/view/frontend/templates/onepage.phtml(21): Magento\Checkout\Block\Onepage->getJsLayout()
#12 /var/www/html/dev.petceutics.com.au/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/d...')
#13 /var/www/html/dev.petceutics.com.au/vendor/magento/framework/View/Element/Template.php(270): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Checkout\Block\Onepage), '/var/www/html/d...', Array)

**Comment by kleestb** [comment]
We have the same issues - more than one year later! Any support here?

**Comment by incarnate** [comment]
Hi @kleestb 

Thanks for the post! 
I've just had a quick look at this - I can see the error would occur if a Connection Type isn't configured for the eWAY Magento 2 module. If you have set that and are still getting the error, your best bet would be to reach out to [eWAY support](https://www.eway.com.au/contact-us/active-merchant/).

As this repo is for the PHP SDK and not the Magento 2 module, there isn't much more that can be done here.
