### ISSUE TITLE
1.4.0 no longer available via packagist?

### ISSUE THREAD

**Issue by johnorourke** [eWAYPayment/eway-rapid-php#24]
The eWay Magento module 3.1.0 requires eway-rapid-php >=1.4 but that version isn't available via packagist: https://packagist.org/packages/eway/eway-rapid-php

Looking at our composer.lock file, it *was* available recently because we have it installed, but now we can't run composer update.

Am I missing something simple?

**Comment by incarnate** [comment]
Thanks for opening the issue @johnorourke - you are right that it was listed until fairly recently. I'm not clear what has changed with Packagist to delist v1.4.0 when nothing changed on our end, but I've fixed the error in composer.json and v1.4.0 is back up again. Apologies for the inconvenience!
