### ISSUE TITLE
PHP 7.0 syntax being used

### ISSUE THREAD

**Issue by benignant** [eWAYPayment/eway-rapid-php#35]
PR https://github.com/eWAYPayment/eway-rapid-php/pull/26 added some code that uses `??` (added in PHP 7.0).

https://github.com/eWAYPayment/eway-rapid-php/blob/6a2a038e34c3a784b7db580dc9b21bcaeba35ed2/src/Rapid/Client.php#L447

This library is meant to be compatible with [PHP 5.4 or greater](https://github.com/eWAYPayment/eway-rapid-php?tab=readme-ov-file#install).

**Comment by incarnate** [comment]
Thanks for getting in touch benignant - we've just published version 1.4.2 which resolves this issue.
