### ISSUE TITLE
V6010 (invalid TransactionType) whenever I try Direct Connection via PHP SDK in sandbox with PCI enabled

### ISSUE THREAD

**Issue by meglio** [eWAYPayment/eway-rapid-php#7]
eWay PHP SDK version v1.2.3

I setup my 3 Sandbox accounts (AUS, NZ and UK) to make sure the issue persists everywhere.

I enabled PCI for all of them. I'm using PHP SDK and Direct Connection method. Whenever I create a new transaction, code V6010 is returned, which means "Invalid TransactionType, account not certified for eCome only MOTO or Recurring available".
 
Looks like a bug, unless I'm doing something wrong. And I'm stuck with this and can't test my Direct Connection integration in sandbox.

**Comment by meglio** [comment]
# Request

```php
$api = \Eway\Rapid::createClient($apiKey, $apiPassword, $eWayClientContractMode);
$transResponse = $api->createTransaction(\Eway\Rapid\Enum\ApiMethod::DIRECT, $transactionReq);
```

The value of `$transactionReq`:

![image](https://cloud.githubusercontent.com/assets/282177/14075881/7e3b8588-f524-11e5-9a0b-44bd640f2b96.png)

**Comment by incarnate** [comment]
Hi Anton,

Thanks for submitting this issue. The error message could be more clear, in this instance it is only the first part which is a problem: "Invalid TransactionType"

You should just need to add a [TransactionType](https://eway.io/api-v3/?php#transaction-types) to your request and you should be good to go!

I'll see if we can improve the validation around that field for the next release.

**Comment by meglio** [comment]
Thanks, it worked. Improving the validation around that field would be useful.
