### ISSUE TITLE
Documentation not precise about possible BeagleScore values

### ISSUE THREAD

**Issue by meglio** [eWAYPayment/eway-rapid-php#8]
For PHP DSK, the online documentation says this:

> Fraud score representing the estimated probability that the order is fraud. A value between 0.01 to 100.00 representing the % risk the transaction is fraudulent.

However, when BeagleScore is disabled, the returned value is `-1`, which is not mentioned in the documentation.

**Comment by incarnate** [comment]
Thanks for the suggestion Anton. 

I've just confirmed with our team, with Sandbox the response will always be `-1` unless the "Maximum Risk Score" option in the Beagle settings is set to "Always Fail", then the response will be `101`. Obviously neither of these confirm to the doco as it currently stands.

On production the value will be between `0.01` and `100` as documented - unless Beagle is disabled, in which case the response will be `0`.

I'm writing a clarification for these for our next doco update, thanks again for raising it!

**Comment by incarnate** [comment]
The API reference reflects these details now, thanks again for pointing it out!
